# Generated by Django 3.1.7 on 2021-03-31 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod Łóżka')),
                ('localisation', models.CharField(blank=True, db_index=True, help_text='Lokalizacja łóżka, np. Paw.B Sala 205, dla poprawnego sortowania należy używać jednego schematu.', max_length=128, verbose_name='Lokalizacja')),
                ('description', models.CharField(blank=True, db_index=True, help_text='Wewnętrzny opis łóżka.', max_length=128, verbose_name='Opis')),
                ('respirator', models.BooleanField(default=False, verbose_name='Respirator')),
                ('oxygen', models.BooleanField(default=False, verbose_name='Oxygen')),
                ('child', models.BooleanField(default=False, verbose_name='Child')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital', verbose_name='Hospital')),
                ('specialisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='hospitals.specialisation')),
            ],
            options={
                'ordering': ['localisation', 'code'],
            },
        ),
    ]
