# Generated by Django 3.1.7 on 2021-03-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa Specjalizacji/Oddziału')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod Szpitala')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa Szpitala')),
                ('address', models.TextField(blank=True, verbose_name='Adres Szpitala')),
                ('respirators', models.IntegerField(default=0, verbose_name='Mobilne Respiratory')),
                ('oxygens', models.IntegerField(default=0, verbose_name='Mobilny Tlen')),
                ('specialisations', models.ManyToManyField(blank=True, related_name='hospitals', to='hospitals.Specialisation', verbose_name='Dostępne Specjalizacje')),
            ],
        ),
    ]
