# Generated by Django 3.1.7 on 2021-03-31 04:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTicket',
            fields=[
                ('delete_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('delete_reason', models.CharField(max_length=1024, verbose_name='Przyczyna skasowania')),
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod Biletu')),
                ('description', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Opis')),
                ('respirator', models.BooleanField(verbose_name='Potrzebny Respirator')),
                ('oxygen', models.BooleanField(verbose_name='Potrzebny Tlen')),
                ('child', models.BooleanField(verbose_name='Potrzebne Łóżko Dziecięce')),
                ('use_respirator', models.BooleanField(verbose_name='Użyty Mobilny Respirator')),
                ('use_oxygen', models.BooleanField(verbose_name='Użyty Mobilny Tlen')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Ważności')),
                ('canceled', models.BooleanField(verbose_name='Anulowane')),
                ('canceled_reason', models.TextField(blank=True, null=True, verbose_name='Przyczyna Anulowania')),
                ('created_on', models.DateTimeField()),
                ('last_modified_on', models.DateTimeField()),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beds.bed', verbose_name='Łóżko')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital', verbose_name='Szpital')),
                ('prev', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.deletedticket')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('code', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, verbose_name='Kod Biletu')),
                ('number', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Numer Pacjenta')),
                ('respirator', models.BooleanField(default=False, verbose_name='Potrzebny Respirator')),
                ('oxygen', models.BooleanField(default=False, verbose_name='Potrzebny Tlen')),
                ('child', models.BooleanField(default=False, verbose_name='Potrzebne Łóżko Dziecięce')),
                ('use_respirator', models.BooleanField(default=False, verbose_name='Użyty Mobilny Respirator')),
                ('use_oxygen', models.BooleanField(default=False, verbose_name='Użyty Mobilny Tlen')),
                ('expiration_date', models.DateTimeField(blank=True, default=tickets.models.default_expiration_date, editable=False, null=True, verbose_name='Data Ważności')),
                ('canceled', models.BooleanField(default=False, editable=False, verbose_name='Anulowane')),
                ('canceled_reason', models.TextField(blank=True, editable=False, null=True, verbose_name='Przyczyna Anulowania')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('last_modified_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.bed', verbose_name='Łóżko')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital', verbose_name='Szpital')),
                ('prev', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.deletedticket')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
